apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: {{.Release.Name}}-controller
  name: {{.Release.Name}}-{{.Release.Name}}-controller
  namespace: {{.Release.Name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      control-plane: {{.Release.Name}}-controller
  template:
    metadata:
      labels:
        control-plane: {{.Release.Name}}-controller
    spec:
      containers:
        - args:
            - --enable-leader-election
          command:
            - /controller
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          name: controller
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
      terminationGracePeriodSeconds: 10
