image:
  repository: "ghcr.io/alexellis/registry-creds"
  tag: "0.2.6"
  pullPolicy: IfNotPresent
resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 100m
      memory: 45Mi
replicaCount: 1
dockerConfigJsonBase64Encoded: "eyJhdXRo...REPLACE_ME"
