{{if .Values.defaultClusterPullSecret.enabled}}
apiVersion: ops.alexellis.io/v1
kind: ClusterPullSecret
metadata:
  name: docker-registry-{{.Values.defaultClusterPullSecret.dockerConfigJsonBase64Encoded | sha256sum}}
spec:
  secretRef:
    name: dockerhub-config-{{.Values.defaultClusterPullSecret.dockerConfigJsonBase64Encoded | sha256sum}}
    namespace: {{.Release.Namespace}}
{{end}}