{{if .Values.defaultClusterPullSecret.enabled}}
apiVersion: ops.alexellis.io/v1
kind: ClusterPullSecret
metadata:
  name: docker-registry
spec:
  secretRef:
    name: dockerhub-config-json
    namespace: {{.Release.Namespace}}
{{end}}